creation_rules:
  - path_regex: hosts/theau-vps/secrets\.enc\.yaml$
    age:
      - age1c75r3vmlttna6qkw85s2yke6whtn50x5sqnv0cftm648mcm2xqgqyf2e5w
  - path_regex: hosts/nas-kot/secrets\.enc\.yaml$
    age:
      - age1c75r3vmlttna6qkw85s2yke6whtn50x5sqnv0cftm648mcm2xqgqyf2e5w
